project:
  type: website

website:
  title: "Coal exports"
  navbar:
    left:
      - href: docs/index.html
        text: Home
      - data_collection/tidycensus_data.html

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true