project:
  type: website
  output-dir: docs

website:
  title: "Coal project"
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Census Data"
        href: census_data.html

files:
  exclude:
    - "data/**"
    - "coal_export_points.Rmd"
    - "coal_export_points.html"
    - "tidycensus_data.Rmd"        