project:
  type: website
  output-dir: docs

website:
  title: ""
  sidebar:
  style: "docked"
  search: false
  contents:
    - section: "Data collection"
      contents:
        - text: "Census Data"
        - href: census_data.html

files:
  include:
    - index.html
    - census_data.html
  exclude:
    - "data/**"
    - "coal_export_points.Rmd"
    - "coal_export_points.html"
    - "tidycensus_data.Rmd"        



