project:
  type: website
  output-dir: docs

website:
  title: "Coal Dust Project"
  search: false
  navbar:
    left:
      - text: "Home"
        href: index.html
      - text: "Census Data"
        href: tidycensus_data.html
      - text: "Mapping Coal Export Locations"
        href: coal_exports.html

files:
  include:
    - index.html
    - census_data.html
    - coal_export_points.html
  exclude:
    - "data/**"
    - coal_export_points.html
   

