project:
  type: website

website:
  title: "Coal exports"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - tidycensus_data.qmd

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true